export const SET_FINDER_ID_ENABLED = "SET_FINDER_ID_ENABLED";
export const SET_FINDER_CLASS_ENABLED = "SET_FINDER_CLASS_ENABLED";
export const SET_FINDER_TAG_ENABLED = "SET_FINDER_TAG_ENABLED";
export const ADD_FINDER_ID_FILTER = "ADD_FINDER_ID_FILTER";
export const DELETE_FINDER_ID_FILTER = "DELETE_FINDER_ID_FILTER";
export const ADD_FINDER_CLASS_FILTER = "ADD_FINDER_CLASS_FILTER";
export const DELETE_FINDER_CLASS_FILTER = "DELETE_FINDER_CLASS_FILTER";
export const ADD_FINDER_TAG_FILTER = "ADD_FINDER_TAG_FILTER";
export const DELETE_FINDER_TAG_FILTER = "DELETE_FINDER_TAG_FILTER";
export const SET_FINDER_SEED_MIN_LENGTH = "SET_FINDER_SEED_MIN_LENGTH";
export const SET_FINDER_OPTIMIZED_MIN_LENGTH =
  "SET_FINDER_OPTIMIZED_MIN_LENGTH";
