export const SET_BOTTOM_TAB_INDEX = "SET_BOTTOM_TAB_INDEX";
export const CLEAR_CONSOLE = "CLEAR_CONSOLE";
export const EXIT_APPLICATION = "EXIT_APPLICATION";
export const ADD_OR_REMOVE_SELECTED_ELEMENT = "ADD_OR_REMOVE_SELECTED_ELEMENT";
export const ONLY_SELECT_SELECTED_ELEMENT = "ONLY_SELECT_SELECTED_ELEMENT";
