export const SET_BOTTOM_TAB_INDEX = "SET_BOTTOM_TAB_INDEX";
export const CLEAR_CONSOLE = "CLEAR_CONSOLE";
export const EXIT_APPLICATION = "EXIT_APPLICATION";
export const USE_AS_SELECTOR_ROOT = "USE_AS_SELECTOR_ROOT";
