export const SET_MOUSEOVER_ELEMENT = "SET_MOUSEOVER_ELEMENT";
export const SET_MOUSEOUT_ELEMENT = "SET_MOUSEOUT_ELEMENT";
export const ONLY_SELECT_SELECTED_ELEMENT = "ONLY_SELECT_SELECTED_ELEMENT";
export const CHANGE_SELECTION_TO_PARENT = "CHANGE_SELECTION_TO_PARENT";
export const CHANGE_SELECTION_TO_FIRST_CHILD =
  "CHANGE_SELECTION_TO_FIRST_CHILD";
export const CHANGE_SELECTION_TO_NEXT_SIBLING =
  "CHANGE_SELECTION_TO_NEXT_SIBLING";
export const CHANGE_SELECTION_TO_PREV_SIBLING =
  "CHANGE_SELECTION_TO_PREV_SIBLING";
export const CHANGE_SELECTOR_ROOT = "CHANGE_SELECTOR_ROOT";
export const ENABLE_SELECTOR_ROOT_EDIT = "ENABLE_SELECTOR_ROOT_EDIT";
export const SAVE_TEMP_SELECTOR_ROOT = "SAVE_TEMP_SELECTOR_ROOT";
export const CANCEL_TEMP_SELECTOR_ROOT = "CANCEL_TEMP_SELECTOR_ROOT";
export const RESET_SELECTOR_ROOT = "RESET_SELECTOR_ROOT";
export const SET_TEMP_SELECTOR = "SET_TEMP_SELECTOR";
export const DO_TEST_SELECTOR_HIGHLIGHT = "DO_TEST_SELECTOR_HIGHLIGHT";
export const STOP_TEST_SELECTOR_HIGHLIGHT = "STOP_TEST_SELECTOR_HIGHLIGHT";
export const COPY_SELECTOR_TO_CLIPBOARD = "COPY_SELECTOR_TO_CLIPBOARD";
export const USE_AS_SELECTOR_ROOT = "USE_AS_SELECTOR_ROOT";
export const EXIT_APPLICATION = "EXIT_APPLICATION";
export const GENERATE_SELECTOR = "GENERATE_SELECTOR";
export const SET_BOTTOM_TAB_INDEX = "SET_BOTTOM_TAB_INDEX";
